### ISSUE TITLE
fail import nextcord !

### ISSUE THREAD

**Issue by Whyren666** [dkoz/evrima-bot#1]
![image](https://github.com/user-attachments/assets/e19490a6-4ee0-4bf3-96e3-6ae82406c228)
pls help

**Comment by dkoz** [comment]
> ![image](https://private-user-images.githubusercontent.com/172902394/387398951-e19490a6-4ee0-4bf3-96e3-6ae82406c228.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODg1ODEsIm5iZiI6MTczMjI4ODI4MSwicGF0aCI6Ii8xNzI5MDIzOTQvMzg3Mzk4OTUxLWUxOTQ5MGE2LTRlZTAtNGJmMy05NmUzLTZhZTgyNDA2YzIyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEyMlQxNTExMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDRkMGVhZTk1ODQ0N2Q2MWI1NzYwYWIyYzQ4YjliZDViMDk1ODU4NTY2MDk2YzQ3YjljMzUzMjk1YjM4NzNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.i1mmLVWc8Zsmy36WKO_ICecstdK_Hspoq05ezhZaZ-c) pls help

Install the requirements.

```
pip install setuptools
pip install -r requirements.txt
```
